In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
weather=pd.read_csv("weatherAUS.csv")

In [4]:
weather.head(4)

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,0.0,No
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,0.0,No
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,0.0,No
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No,1.0,No

In [5]:
import pandas as pd

In [6]:
weather=pd.read_csv("weatherAUS.csv")

In [7]:
weather.tail(4)

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
142189,2017-06-21,Uluru,2.8,23.4,0.0,NaN,NaN,E,31.0,SE,...,24.0,1024.6,1020.3,NaN,NaN,10.1,22.4,No,0.0,No
142190,2017-06-22,Uluru,3.6,25.3,0.0,NaN,NaN,NNW,22.0,SE,...,21.0,1023.5,1019.1,NaN,NaN,10.9,24.5,No,0.0,No
142191,2017-06-23,Uluru,5.4,26.9,0.0,NaN,NaN,N,37.0,SE,...,24.0,1021.0,1016.8,NaN,NaN,12.5,26.1,No,0.0,No
142192,2017-06-24,Uluru,7.8,27.0,0.0,NaN,NaN,SE,28.0,SSE,...,24.0,1019.4,1016.5,3.0,2.0,15.1,26.0,No,0.0,No

In [8]:
weather.index

RangeIndex(start=0, stop=142193, step=1)

In [9]:
weather.columns

Index(['Date', 'Location', 'MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation',
       'Sunshine', 'WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm',
       'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
       'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am',
       'Temp3pm', 'RainToday', 'RISK_MM', 'RainTomorrow'],
      dtype='object')

In [10]:
weather.shape

(142193, 24)

In [11]:
weather.dtypes

Date              object
Location          object
MinTemp          float64
MaxTemp          float64
Rainfall         float64
Evaporation      float64
Sunshine         float64
WindGustDir       object
WindGustSpeed    float64
WindDir9am        object
WindDir3pm        object
WindSpeed9am     float64
WindSpeed3pm     float64
Humidity9am      float64
Humidity3pm      float64
Pressure9am      float64
Pressure3pm      float64
Cloud9am         float64
Cloud3pm         float64
Temp9am          float64
Temp3pm          float64
RainToday         object
RISK_MM          float64
RainTomorrow      object
dtype: object

In [12]:
weather.columns.values

array(['Date', 'Location', 'MinTemp', 'MaxTemp', 'Rainfall',
       'Evaporation', 'Sunshine', 'WindGustDir', 'WindGustSpeed',
       'WindDir9am', 'WindDir3pm', 'WindSpeed9am', 'WindSpeed3pm',
       'Humidity9am', 'Humidity3pm', 'Pressure9am', 'Pressure3pm',
       'Cloud9am', 'Cloud3pm', 'Temp9am', 'Temp3pm', 'RainToday',
       'RISK_MM', 'RainTomorrow'], dtype=object)

In [13]:
weather.describe(include="all")

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
count,142193,142193,141556.000000,141871.000000,140787.000000,81350.000000,74377.000000,132863,132923.000000,132180,...,138583.000000,128179.000000,128212.000000,88536.000000,85099.000000,141289.000000,139467.000000,140787,142193.000000,142193
unique,3436,49,NaN,NaN,NaN,NaN,NaN,16,NaN,16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,2
top,2013-12-01,Canberra,NaN,NaN,NaN,NaN,NaN,W,NaN,N,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,No
freq,49,3418,NaN,NaN,NaN,NaN,NaN,9780,NaN,11393,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,109332,NaN,110316
mean,NaN,NaN,12.186400,23.226784,2.349974,5.469824,7.624853,NaN,39.984292,NaN,...,51.482606,1017.653758,1015.258204,4.437189,4.503167,16.987509,21.687235,NaN,2.360682,NaN
std,NaN,NaN,6.403283,7.117618,8.465173,4.188537,3.781525,NaN,13.588801,NaN,...,20.797772,7.105476,7.036677,2.887016,2.720633,6.492838,6.937594,NaN,8.477969,NaN
min,NaN,NaN,-8.500000,-4.800000,0.000000,0.000000,0.000000,NaN,6.000000,NaN,...,0.000000,980.500000,977.100000,0.000000,0.000000,-7.200000,-5.400000,NaN,0.000000,NaN
25%,NaN,NaN,7.600000,17.900000,0.000000,2.600000,4.900000,NaN,31.000000,NaN,...,37.000000,1012.900000,1010.400000,1.000000,2.000000,12.300000,16.600000,NaN,0.000000,NaN
50%,NaN,NaN,12.000000,22.600000,0.000000,4.800000,8.500000,NaN,39.000000,NaN,...,52.000000,1017.600000,1015.200000,5.000000,5.000000,16.700000,21.100000,NaN,0.000000,NaN
75%,NaN,NaN,16.800000,28.200000,0.800000,7.400000,10.600000,NaN,48.000000,NaN,...,66.000000,1022.400000,1020.000000,7.000000,7.000000,21.600000,26.400000,NaN,0.800000,NaN
max,NaN,NaN,33.900000,48.100000,371.000000,145.000000,14.500000,NaN,135.000000,NaN,...,100.000000,1041.000000,1039.600000,9.000000,9.000000,40.200000,46.700000,NaN,371.000000,NaN

In [14]:
weather["Location"]

0         Albury
1         Albury
2         Albury
3         Albury
4         Albury
           ...
142188     Uluru
142189     Uluru
142190     Uluru
142191     Uluru
142192     Uluru
Name: Location, Length: 142193, dtype: object

In [15]:
weather.sort_index(axis=1,ascending=False)

,WindSpeed9am,WindSpeed3pm,WindGustSpeed,WindGustDir,WindDir9am,WindDir3pm,Temp9am,Temp3pm,Sunshine,Rainfall,...,Pressure3pm,MinTemp,MaxTemp,Location,Humidity9am,Humidity3pm,Evaporation,Date,Cloud9am,Cloud3pm
0,20.0,24.0,44.0,W,W,WNW,16.9,21.8,NaN,0.6,...,1007.1,13.4,22.9,Albury,71.0,22.0,NaN,2008-12-01,8.0,NaN
1,4.0,22.0,44.0,WNW,NNW,WSW,17.2,24.3,NaN,0.0,...,1007.8,7.4,25.1,Albury,44.0,25.0,NaN,2008-12-02,NaN,NaN
2,19.0,26.0,46.0,WSW,W,WSW,21.0,23.2,NaN,0.0,...,1008.7,12.9,25.7,Albury,38.0,30.0,NaN,2008-12-03,NaN,2.0
3,11.0,9.0,24.0,NE,SE,E,18.1,26.5,NaN,0.0,...,1012.8,9.2,28.0,Albury,45.0,16.0,NaN,2008-12-04,NaN,NaN
4,7.0,20.0,41.0,W,ENE,NW,17.8,29.7,NaN,1.0,...,1006.0,17.5,32.3,Albury,82.0,33.0,NaN,2008-12-05,7.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142188,15.0,13.0,31.0,E,ESE,E,9.4,20.9,NaN,0.0,...,1021.2,3.5,21.8,Uluru,59.0,27.0,NaN,2017-06-20,NaN,NaN
142189,13.0,11.0,31.0,E,SE,ENE,10.1,22.4,NaN,0.0,...,1020.3,2.8,23.4,Uluru,51.0,24.0,NaN,2017-06-21,NaN,NaN
142190,13.0,9.0,22.0,NNW,SE,N,10.9,24.5,NaN,0.0,...,1019.1,3.6,25.3,Uluru,56.0,21.0,NaN,2017-06-22,NaN,NaN
142191,9.0,9.0,37.0,N,SE,WNW,12.5,26.1,NaN,0.0,...,1016.8,5.4,26.9,Uluru,53.0,24.0,NaN,2017-06-23,NaN,NaN
142192,13.0,7.0,28.0,SE,SSE,N,15.1,26.0,NaN,0.0,...,1016.5,7.8,27.0,Uluru,51.0,24.0,NaN,2017-06-24,3.0,2.0

In [16]:
weather.sort_values(by="Location")

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
94847,2011-05-16,Adelaide,5.2,16.6,0.0,3.6,8.8,NE,26.0,NaN,...,44.0,1034.6,1030.6,NaN,NaN,10.6,16.2,No,0.0,No
95911,2014-08-14,Adelaide,9.8,15.5,0.0,2.2,NaN,SE,31.0,E,...,47.0,1035.6,1031.4,NaN,NaN,11.7,14.7,No,0.0,No
95912,2014-08-15,Adelaide,8.5,20.3,0.0,2.0,NaN,E,48.0,WNW,...,40.0,1026.8,1022.9,NaN,NaN,15.0,18.1,No,0.0,No
95913,2014-08-16,Adelaide,10.3,14.0,0.0,NaN,NaN,SE,46.0,SW,...,60.0,1021.6,1019.4,NaN,NaN,10.3,13.0,No,1.8,Yes
95914,2014-08-17,Adelaide,9.4,16.2,1.8,NaN,NaN,SSE,39.0,S,...,73.0,1021.4,1020.5,NaN,NaN,11.6,13.5,Yes,0.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104165,2012-05-09,Woomera,13.1,25.3,0.0,15.4,9.2,SSE,35.0,S,...,32.0,1019.7,1018.0,4.0,1.0,18.0,24.7,No,0.2,No
104166,2012-05-10,Woomera,13.4,25.1,0.2,7.0,7.9,SE,48.0,S,...,29.0,1022.2,1019.1,3.0,1.0,15.6,24.3,No,0.0,No
104167,2012-05-11,Woomera,10.8,22.3,0.0,5.8,NaN,S,41.0,S,...,34.0,1023.8,1021.3,0.0,NaN,15.8,21.4,No,0.0,No
104159,2012-05-03,Woomera,7.1,17.7,0.0,6.2,NaN,SE,35.0,SE,...,26.0,1028.1,1023.7,0.0,0.0,11.7,17.0,No,0.0,No
105809,2017-01-17,Woomera,22.7,43.5,0.0,NaN,NaN,N,41.0,ENE,...,7.0,1008.5,1005.5,NaN,NaN,31.2,41.8,No,0.0,No

In [17]:
weather.iloc[5]

Date             2008-12-06
Location             Albury
MinTemp                14.6
MaxTemp                29.7
Rainfall                0.2
Evaporation             NaN
Sunshine                NaN
WindGustDir             WNW
WindGustSpeed          56.0
WindDir9am                W
WindDir3pm                W
WindSpeed9am           19.0
WindSpeed3pm           24.0
Humidity9am            55.0
Humidity3pm            23.0
Pressure9am          1009.2
Pressure3pm          1005.4
Cloud9am                NaN
Cloud3pm                NaN
Temp9am                20.6
Temp3pm                28.9
RainToday                No
RISK_MM                 0.0
RainTomorrow             No
Name: 5, dtype: object

In [18]:
weather[0:3]

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,0.0,No
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,0.0,No
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,0.0,No

In [19]:
weather.loc[:,["Date","Location"]]

              Date Location
0       2008-12-01   Albury
1       2008-12-02   Albury
2       2008-12-03   Albury
3       2008-12-04   Albury
4       2008-12-05   Albury
...            ...      ...
142188  2017-06-20    Uluru
142189  2017-06-21    Uluru
142190  2017-06-22    Uluru
142191  2017-06-23    Uluru
142192  2017-06-24    Uluru

[142193 rows x 2 columns]

In [20]:
weather.iloc[:6, :]

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,0.0,No
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,0.0,No
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,0.0,No
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No,1.0,No
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,0.2,No
5,2008-12-06,Albury,14.6,29.7,0.2,NaN,NaN,WNW,56.0,W,...,23.0,1009.2,1005.4,NaN,NaN,20.6,28.9,No,0.0,No

In [21]:
weather.iloc[:, :5]

              Date Location  MinTemp  MaxTemp  Rainfall
0       2008-12-01   Albury     13.4     22.9       0.6
1       2008-12-02   Albury      7.4     25.1       0.0
2       2008-12-03   Albury     12.9     25.7       0.0
3       2008-12-04   Albury      9.2     28.0       0.0
4       2008-12-05   Albury     17.5     32.3       1.0
...            ...      ...      ...      ...       ...
142188  2017-06-20    Uluru      3.5     21.8       0.0
142189  2017-06-21    Uluru      2.8     23.4       0.0
142190  2017-06-22    Uluru      3.6     25.3       0.0
142191  2017-06-23    Uluru      5.4     26.9       0.0
142192  2017-06-24    Uluru      7.8     27.0       0.0

[142193 rows x 5 columns]

In [22]:
weather.iloc[:4, :5]

         Date Location  MinTemp  MaxTemp  Rainfall
0  2008-12-01   Albury     13.4     22.9       0.6
1  2008-12-02   Albury      7.4     25.1       0.0
2  2008-12-03   Albury     12.9     25.7       0.0
3  2008-12-04   Albury      9.2     28.0       0.0

In [23]:
weather.isnull()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,False,False,False,False,False,True,True,False,False,False,...,False,False,False,False,True,False,False,False,False,False
1,False,False,False,False,False,True,True,False,False,False,...,False,False,False,True,True,False,False,False,False,False
2,False,False,False,False,False,True,True,False,False,False,...,False,False,False,True,False,False,False,False,False,False
3,False,False,False,False,False,True,True,False,False,False,...,False,False,False,True,True,False,False,False,False,False
4,False,False,False,False,False,True,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142188,False,False,False,False,False,True,True,False,False,False,...,False,False,False,True,True,False,False,False,False,False
142189,False,False,False,False,False,True,True,False,False,False,...,False,False,False,True,True,False,False,False,False,False
142190,False,False,False,False,False,True,True,False,False,False,...,False,False,False,True,True,False,False,False,False,False
142191,False,False,False,False,False,True,True,False,False,False,...,False,False,False,True,True,False,False,False,False,False
142192,False,False,False,False,False,True,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [24]:
weather.isnull().any()

Date             False
Location         False
MinTemp           True
MaxTemp           True
Rainfall          True
Evaporation       True
Sunshine          True
WindGustDir       True
WindGustSpeed     True
WindDir9am        True
WindDir3pm        True
WindSpeed9am      True
WindSpeed3pm      True
Humidity9am       True
Humidity3pm       True
Pressure9am       True
Pressure3pm       True
Cloud9am          True
Cloud3pm          True
Temp9am           True
Temp3pm           True
RainToday         True
RISK_MM          False
RainTomorrow     False
dtype: bool

In [25]:
weather.isnull().sum(axis=1)

0         3
1         4
2         3
3         4
4         2
         ..
142188    4
142189    4
142190    4
142191    4
142192    2
Length: 142193, dtype: int64

In [26]:
weather.isnull().sum()

Date                 0
Location             0
MinTemp            637
MaxTemp            322
Rainfall          1406
Evaporation      60843
Sunshine         67816
WindGustDir       9330
WindGustSpeed     9270
WindDir9am       10013
WindDir3pm        3778
WindSpeed9am      1348
WindSpeed3pm      2630
Humidity9am       1774
Humidity3pm       3610
Pressure9am      14014
Pressure3pm      13981
Cloud9am         53657
Cloud3pm         57094
Temp9am            904
Temp3pm           2726
RainToday         1406
RISK_MM              0
RainTomorrow         0
dtype: int64