In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df=pd.read_csv("Employee_Salary_Dataset.csv")

In [5]:
print(df)

    ID  Experience_Years  Age  Gender    Salary
0    1                 5   28  Female    250000
1    2                 1   21    Male     50000
2    3                 3   23  Female    170000
3    4                 2   22    Male     25000
4    5                 1   17    Male     10000
5    6                25   62    Male   5001000
6    7                19   54  Female    800000
7    8                 2   21  Female      9000
8    9                10   36  Female     61500
9   10                15   54  Female    650000
10  11                 4   26  Female    250000
11  12                 6   29    Male   1400000
12  13                14   39    Male   6000050
13  14                11   40    Male    220100
14  15                 2   23    Male      7500
15  16                 4   27  Female     87000
16  17                10   34  Female    930000
17  18                15   54  Female   7900000
18  19                 2   21    Male     15000
19  20                10   36    Male    330000
20  21                15   54    Male   6570000
21  22                 4   26    Male     25000
22  23                 5   29    Male   6845000
23  24                 1   21  Female      6000
24  25                 4   23  Female      8900
25  26                 3   22  Female     20000
26  27                 1   18    Male      3000
27  28                27   62  Female  10000000
28  29                19   54  Female   5000000
29  30                 2   21  Female      6100
30  31                10   34    Male     80000
31  32                15   54    Male    900000
32  33                20   55  Female   1540000
33  34                19   53  Female   9300000
34  35                16   49    Male   7600000

In [6]:
df.mean(numeric_only=True)

ID                  1.800000e+01
Experience_Years    9.200000e+00
Age                 3.548571e+01
Salary              2.059147e+06
dtype: float64

In [7]:
df.loc[:,'Age'].mean()

35.48571428571429

In [8]:
df.select_dtypes(include='number').mean(axis=1)[0:4]

0    62508.50
1    12506.00
2    42507.25
3     6257.00
dtype: float64

In [11]:
df.median(numeric_only=True)

ID                      18.0
Experience_Years         6.0
Age                     29.0
Salary              250000.0
dtype: float64

In [ ]:
df.loc[:,'Age'].median()

29.0

In [ ]:
df.median(axis=1)[0:4]

C:\Users\Parth S Kourwar\AppData\Local\Temp\ipykernel_10460\381455229.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.median(axis=1)[0:4]

0    16.5
1    11.5
2    13.0
3    13.0
dtype: float64

In [ ]:
df.mode()

    ID  Experience_Years   Age  Gender    Salary
0    1               2.0  54.0  Female   25000.0
1    2               NaN   NaN     NaN  250000.0
2    3               NaN   NaN     NaN       NaN
3    4               NaN   NaN     NaN       NaN
4    5               NaN   NaN     NaN       NaN
5    6               NaN   NaN     NaN       NaN
6    7               NaN   NaN     NaN       NaN
7    8               NaN   NaN     NaN       NaN
8    9               NaN   NaN     NaN       NaN
9   10               NaN   NaN     NaN       NaN
10  11               NaN   NaN     NaN       NaN
11  12               NaN   NaN     NaN       NaN
12  13               NaN   NaN     NaN       NaN
13  14               NaN   NaN     NaN       NaN
14  15               NaN   NaN     NaN       NaN
15  16               NaN   NaN     NaN       NaN
16  17               NaN   NaN     NaN       NaN
17  18               NaN   NaN     NaN       NaN
18  19               NaN   NaN     NaN       NaN
19  20               NaN   NaN     NaN       NaN
20  21               NaN   NaN     NaN       NaN
21  22               NaN   NaN     NaN       NaN
22  23               NaN   NaN     NaN       NaN
23  24               NaN   NaN     NaN       NaN
24  25               NaN   NaN     NaN       NaN
25  26               NaN   NaN     NaN       NaN
26  27               NaN   NaN     NaN       NaN
27  28               NaN   NaN     NaN       NaN
28  29               NaN   NaN     NaN       NaN
29  30               NaN   NaN     NaN       NaN
30  31               NaN   NaN     NaN       NaN
31  32               NaN   NaN     NaN       NaN
32  33               NaN   NaN     NaN       NaN
33  34               NaN   NaN     NaN       NaN
34  35               NaN   NaN     NaN       NaN

In [ ]:
df.loc[:,'Age'].mode()

0    54
Name: Age, dtype: int64

In [ ]:
df.mode(axis=1)[0:4]

C:\Users\Parth S Kourwar\AppData\Local\Temp\ipykernel_10460\657814072.py:1: UserWarning: Unable to sort modes: '<' not supported between instances of 'str' and 'int'
  df.mode(axis=1)[0:4]
C:\Users\Parth S Kourwar\AppData\Local\Temp\ipykernel_10460\657814072.py:1: UserWarning: Unable to sort modes: '<' not supported between instances of 'str' and 'int'
  df.mode(axis=1)[0:4]
C:\Users\Parth S Kourwar\AppData\Local\Temp\ipykernel_10460\657814072.py:1: UserWarning: Unable to sort modes: '<' not supported between instances of 'str' and 'int'
  df.mode(axis=1)[0:4]
C:\Users\Parth S Kourwar\AppData\Local\Temp\ipykernel_10460\657814072.py:1: UserWarning: Unable to sort modes: '<' not supported between instances of 'str' and 'int'
  df.mode(axis=1)[0:4]
C:\Users\Parth S Kourwar\AppData\Local\Temp\ipykernel_10460\657814072.py:1: UserWarning: Unable to sort modes: '<' not supported between instances of 'str' and 'int'
  df.mode(axis=1)[0:4]
C:\Users\Parth S Kourwar\AppData\Local\Temp\ipykernel_10460\657814072.py:1: UserWarning: Unable to sort modes: '<' not supported between instances of 'str' and 'int'
  df.mode(axis=1)[0:4]
C:\Users\Parth S Kourwar\AppData\Local\Temp\ipykernel_10460\657814072.py:1: UserWarning: Unable to sort modes: '<' not supported between instances of 'str' and 'int'
  df.mode(axis=1)[0:4]
C:\Users\Parth S Kourwar\AppData\Local\Temp\ipykernel_10460\657814072.py:1: UserWarning: Unable to sort modes: '<' not supported between instances of 'str' and 'int'
  df.mode(axis=1)[0:4]
C:\Users\Parth S Kourwar\AppData\Local\Temp\ipykernel_10460\657814072.py:1: UserWarning: Unable to sort modes: '<' not supported between instances of 'str' and 'int'
  df.mode(axis=1)[0:4]
C:\Users\Parth S Kourwar\AppData\Local\Temp\ipykernel_10460\657814072.py:1: UserWarning: Unable to sort modes: '<' not supported between instances of 'str' and 'int'
  df.mode(axis=1)[0:4]
C:\Users\Parth S Kourwar\AppData\Local\Temp\ipykernel_10460\657814072.py:1: UserWarning: Unable to sort modes: '<' not supported between instances of 'str' and 'int'
  df.mode(axis=1)[0:4]
C:\Users\Parth S Kourwar\AppData\Local\Temp\ipykernel_10460\657814072.py:1: UserWarning: Unable to sort modes: '<' not supported between instances of 'str' and 'int'
  df.mode(axis=1)[0:4]
C:\Users\Parth S Kourwar\AppData\Local\Temp\ipykernel_10460\657814072.py:1: UserWarning: Unable to sort modes: '<' not supported between instances of 'str' and 'int'
  df.mode(axis=1)[0:4]
C:\Users\Parth S Kourwar\AppData\Local\Temp\ipykernel_10460\657814072.py:1: UserWarning: Unable to sort modes: '<' not supported between instances of 'str' and 'int'
  df.mode(axis=1)[0:4]
C:\Users\Parth S Kourwar\AppData\Local\Temp\ipykernel_10460\657814072.py:1: UserWarning: Unable to sort modes: '<' not supported between instances of 'str' and 'int'
  df.mode(axis=1)[0:4]
C:\Users\Parth S Kourwar\AppData\Local\Temp\ipykernel_10460\657814072.py:1: UserWarning: Unable to sort modes: '<' not supported between instances of 'str' and 'int'
  df.mode(axis=1)[0:4]
C:\Users\Parth S Kourwar\AppData\Local\Temp\ipykernel_10460\657814072.py:1: UserWarning: Unable to sort modes: '<' not supported between instances of 'str' and 'int'
  df.mode(axis=1)[0:4]
C:\Users\Parth S Kourwar\AppData\Local\Temp\ipykernel_10460\657814072.py:1: UserWarning: Unable to sort modes: '<' not supported between instances of 'str' and 'int'
  df.mode(axis=1)[0:4]
C:\Users\Parth S Kourwar\AppData\Local\Temp\ipykernel_10460\657814072.py:1: UserWarning: Unable to sort modes: '<' not supported between instances of 'str' and 'int'
  df.mode(axis=1)[0:4]
C:\Users\Parth S Kourwar\AppData\Local\Temp\ipykernel_10460\657814072.py:1: UserWarning: Unable to sort modes: '<' not supported between instances of 'str' and 'int'
  df.mode(axis=1)[0:4]
C:\Users\Parth S Kourwar\AppData\Local\Temp\ipykernel_10460\657814072.py:1: UserWarning: Unable to sort modes: '<' not supported between instances of 'str' and 'int'
  df.mode(axis=1)[0:4]
C:\Users\Parth S Kourwar\AppData\Local\Temp\ipykernel_10460\657814072.py:1: UserWarning: Unable to sort modes: '<' not supported between instances of 'str' and 'int'
  df.mode(axis=1)[0:4]
C:\Users\Parth S Kourwar\AppData\Local\Temp\ipykernel_10460\657814072.py:1: UserWarning: Unable to sort modes: '<' not supported between instances of 'str' and 'int'
  df.mode(axis=1)[0:4]
C:\Users\Parth S Kourwar\AppData\Local\Temp\ipykernel_10460\657814072.py:1: UserWarning: Unable to sort modes: '<' not supported between instances of 'str' and 'int'
  df.mode(axis=1)[0:4]
C:\Users\Parth S Kourwar\AppData\Local\Temp\ipykernel_10460\657814072.py:1: UserWarning: Unable to sort modes: '<' not supported between instances of 'str' and 'int'
  df.mode(axis=1)[0:4]
C:\Users\Parth S Kourwar\AppData\Local\Temp\ipykernel_10460\657814072.py:1: UserWarning: Unable to sort modes: '<' not supported between instances of 'str' and 'int'
  df.mode(axis=1)[0:4]
C:\Users\Parth S Kourwar\AppData\Local\Temp\ipykernel_10460\657814072.py:1: UserWarning: Unable to sort modes: '<' not supported between instances of 'str' and 'int'
  df.mode(axis=1)[0:4]
C:\Users\Parth S Kourwar\AppData\Local\Temp\ipykernel_10460\657814072.py:1: UserWarning: Unable to sort modes: '<' not supported between instances of 'str' and 'int'
  df.mode(axis=1)[0:4]
C:\Users\Parth S Kourwar\AppData\Local\Temp\ipykernel_10460\657814072.py:1: UserWarning: Unable to sort modes: '<' not supported between instances of 'str' and 'int'
  df.mode(axis=1)[0:4]
C:\Users\Parth S Kourwar\AppData\Local\Temp\ipykernel_10460\657814072.py:1: UserWarning: Unable to sort modes: '<' not supported between instances of 'str' and 'int'
  df.mode(axis=1)[0:4]
C:\Users\Parth S Kourwar\AppData\Local\Temp\ipykernel_10460\657814072.py:1: UserWarning: Unable to sort modes: '<' not supported between instances of 'str' and 'int'
  df.mode(axis=1)[0:4]
C:\Users\Parth S Kourwar\AppData\Local\Temp\ipykernel_10460\657814072.py:1: UserWarning: Unable to sort modes: '<' not supported between instances of 'str' and 'int'
  df.mode(axis=1)[0:4]
C:\Users\Parth S Kourwar\AppData\Local\Temp\ipykernel_10460\657814072.py:1: UserWarning: Unable to sort modes: '<' not supported between instances of 'str' and 'int'
  df.mode(axis=1)[0:4]
C:\Users\Parth S Kourwar\AppData\Local\Temp\ipykernel_10460\657814072.py:1: UserWarning: Unable to sort modes: '<' not supported between instances of 'str' and 'int'
  df.mode(axis=1)[0:4]

   0    1     2       3         4
0  1  5.0  28.0  Female  250000.0
1  2  1.0  21.0    Male   50000.0
2  3  NaN   NaN     NaN       NaN
3  4  2.0  22.0    Male   25000.0

In [ ]:
df.min()

ID                       1
Experience_Years         1
Age                     17
Gender              Female
Salary                3000
dtype: object

In [ ]:
df.loc[:,'Salary'].min(skipna = False)

3000

In [ ]:
df.max()

ID                        35
Experience_Years          27
Age                       62
Gender                  Male
Salary              10000000
dtype: object

In [ ]:
df.loc[:,'Salary'].max(skipna = False)

10000000

In [ ]:
df.std(numeric_only=True)

ID                  1.024695e+01
Experience_Years    7.552950e+00
Age                 1.464355e+01
Salary              3.170124e+06
dtype: float64

In [ ]:
df.loc[:,'Age'].std()

14.643551940884361

In [ ]:
df.std(axis=1)[0:4]

C:\Users\Parth S Kourwar\AppData\Local\Temp\ipykernel_10460\3966588610.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.std(axis=1)[0:4]

0    124994.333900
1     24996.001694
2     84995.167190
3     12495.336570
dtype: float64

In [ ]:
df.groupby(['Salary'])['Age'].mean()

Salary
3000        18.0
6000        21.0
6100        21.0
7500        23.0
8900        23.0
9000        21.0
10000       17.0
15000       21.0
20000       22.0
25000       24.0
50000       21.0
61500       36.0
80000       34.0
87000       27.0
170000      23.0
220100      40.0
250000      27.0
330000      36.0
650000      54.0
800000      54.0
900000      54.0
930000      34.0
1400000     29.0
1540000     55.0
5000000     54.0
5001000     62.0
6000050     39.0
6570000     54.0
6845000     29.0
7600000     49.0
7900000     54.0
9300000     53.0
10000000    62.0
Name: Age, dtype: float64

In [ ]:
df_u=df.rename(columns = {'healthy_eating)':'Age'},inplace =False)
(df_u.groupby(['Salary']).Age.mean())

Salary
3000        18.0
6000        21.0
6100        21.0
7500        23.0
8900        23.0
9000        21.0
10000       17.0
15000       21.0
20000       22.0
25000       24.0
50000       21.0
61500       36.0
80000       34.0
87000       27.0
170000      23.0
220100      40.0
250000      27.0
330000      36.0
650000      54.0
800000      54.0
900000      54.0
930000      34.0
1400000     29.0
1540000     55.0
5000000     54.0
5001000     62.0
6000050     39.0
6570000     54.0
6845000     29.0
7600000     49.0
7900000     54.0
9300000     53.0
10000000    62.0
Name: Age, dtype: float64

In [ ]:
from sklearn import preprocessing
enc = preprocessing.OneHotEncoder()
enc_df = pd.DataFrame(enc.fit_transform(df[['Salary']]).toarray())
enc_df

,0,1,2,3,4,5,6,7,8,9,...,23,24,25,26,27,28,29,30,31,32
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
21,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
23,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
33,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [ ]:
print(df.columns)

Index(['ID', 'Experience_Years', 'Age', 'Gender', 'Salary'], dtype='object')

In [ ]:
df_encode = df_u.join(enc_df)
df_encode

,ID,Experience_Years,Age,Gender,Salary,0,1,2,3,4,...,23,24,25,26,27,28,29,30,31,32
0,1,5,28,Female,250000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2,1,21,Male,50000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3,3,23,Female,170000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4,2,22,Male,25000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5,1,17,Male,10000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,6,25,62,Male,5001000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,7,19,54,Female,800000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,8,2,21,Female,9000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,9,10,36,Female,61500,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,10,15,54,Female,650000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,11,4,26,Female,250000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,12,6,29,Male,1400000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,13,14,39,Male,6000050,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
13,14,11,40,Male,220100,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,15,2,23,Male,7500,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,16,4,27,Female,87000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,17,10,34,Female,930000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,18,15,54,Female,7900000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
18,19,2,21,Male,15000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,20,10,36,Male,330000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,21,15,54,Male,6570000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
21,22,4,26,Male,25000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,23,5,29,Male,6845000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
23,24,1,21,Female,6000,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,25,4,23,Female,8900,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,26,3,22,Female,20000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,27,1,18,Male,3000,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,28,27,62,Female,10000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
28,29,19,54,Female,5000000,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,30,2,21,Female,6100,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30,31,10,34,Male,80000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31,32,15,54,Male,900000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32,33,20,55,Female,1540000,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
33,34,19,53,Female,9300000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34,35,16,49,Male,7600000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0